name = "strike-finance/perpetuals"
version = "0.0.0"
license = "Apache-2.0"
compiler = "v1.1.3"
description = "Aiken contracts for project 'strike-finance/perpetuals'"

[repository]
user = "strike-finance"
project = "perpetuals"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.1.0"
source = "github"
